import 'package:flutter/widgets.dart';

// THIS FILE IS AUTOMATICALLY GENERATED!

class AppIconData extends IconData {
  const AppIconData(int codePoint)
      : super(
    codePoint,
    fontFamily: 'icomoon'
  );
}

/// Icons based on font awesome 6.5.1
@staticIconProvider
class AppIcons {
  static const IconData mosque = AppIconData(0xe92a);
  static const IconData groupUsers = AppIconData(0xe92f);
  static const IconData mosqueLocation = AppIconData(0xe929);
  static const IconData userReload = AppIconData(0xe92b);
  static const IconData addMosque = AppIconData(0xe910);
  static const IconData home = AppIconData(0xe923);
  static const IconData slideArrow = AppIconData(0xe921);
  static const IconData draft = AppIconData(0xe90b);
  static const IconData addIcon = AppIconData(0xe901);
  static const IconData cancel = AppIconData(0xe908);
  static const IconData bar = AppIconData(0xe905);
  static const IconData moonStar = AppIconData(0xe928);
  static const IconData logout = AppIconData(0xe90c);
}
